import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import { Providers } from './providers'
import { Button, Link, Navbar, NavbarBrand, NavbarContent, NavbarItem } from '@nextui-org/react'
import Logo from '../components/Logo.png'
import clsx from 'clsx'
// import { Image } from 'next/image'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function NavBar(){
  return <nav className='bg-white/10 rounded-md  max-w-7xl h-12 mx-auto flex  items-center px-5'>
    <div className='flex justify-between w-full'>
    <p className='text-3xl'>KODE</p>
    <div className='text-2xl flex gap-7'>
      <div className=''>
        FEATURES
      </div>
      <div>
        ABOUT
      </div>
      <div>
        DOCS
      </div>
    </div>
    <div>
      <Button  color='primary' size='sm' className='ml-3'>Buy Me Coffee</Button>
    </div>
    </div>
  </nav>
}

function Footer(){
return <nav className='bg-white/10 rounded-md  max-w-7xl h-12 mx-auto w-full flex mt-auto justify-center  items-center px-5'>
Crafted with ❤️ by <Link href='http://dhananjaay.dev' color='primary' className='ml-1'>Dhananjay Senday</Link>
</nav>
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className+" dark text-foreground bg-background  flex-col shrink-0 flex p-3 h-screen"}>
      <Providers>
        <NavBar/>
      
{/* <div className='flex-grow'> */}

      {children}
{/* </div> */}
     
      {/* <div className='select-none relative flex flex-col'>
          <div className='select-none fixed  block opacity-70 '>
            <img src={"https://nextui.org/gradients/docs-left.png"} alt='docs left background' draggable={false} className='relative z-10 select-none shadow-black/5  shadow-none transition-transform-opacity motion-reduce:transition-none !duration-300 rounded-large' />
          </div>
          <div className='fixed block opacity-70 -top-[80%] -right-[60%] 2xl:-top-[60%] 2xl:-right-[45%] z-0 rotate-12 select-none'>
            <img src='https://nextui.org/gradients/docs-right.png' draggable={false} alt='docs right background' className='relative z-10 select-none  shadow-black/5  shadow-none transition-transform-opacity motion-reduce:transition-none !duration-300 rounded-large'/>
          </div>
        </div> */}

        </Providers>
        <Footer/>
      </body>
    </html>
  )
}
